# Generated by Django 4.2.10 on 2024-04-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_rename_name_userinfo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesWorked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_id', models.CharField(blank=True, db_column='MOVIE_ID', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=255, null=True)),
                ('alias', models.CharField(blank=True, db_column='ALIAS', max_length=255, null=True)),
                ('actors', models.CharField(blank=True, db_column='ACTORS', max_length=255, null=True)),
                ('cover', models.CharField(blank=True, db_column='COVER', max_length=255, null=True)),
                ('directors', models.CharField(blank=True, db_column='DIRECTORS', max_length=255, null=True)),
                ('douban_score', models.CharField(blank=True, db_column='DOUBAN_SCORE', max_length=255, null=True)),
                ('douban_votes', models.CharField(blank=True, db_column='DOUBAN_VOTES', max_length=255, null=True)),
                ('genres', models.CharField(blank=True, db_column='GENRES', max_length=255, null=True)),
                ('imdb_id', models.CharField(blank=True, db_column='IMDB_ID', max_length=255, null=True)),
                ('languages', models.CharField(blank=True, db_column='LANGUAGES', max_length=255, null=True)),
                ('mins', models.CharField(blank=True, db_column='MINS', max_length=255, null=True)),
                ('official_site', models.CharField(blank=True, db_column='OFFICIAL_SITE', max_length=255, null=True)),
                ('regions', models.CharField(blank=True, db_column='REGIONS', max_length=255, null=True)),
                ('release_date', models.CharField(blank=True, db_column='RELEASE_DATE', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, db_column='SLUG', max_length=255, null=True)),
                ('storyline', models.CharField(blank=True, db_column='STORYLINE', max_length=8000, null=True)),
                ('tags', models.CharField(blank=True, db_column='TAGS', max_length=255, null=True)),
                ('year', models.CharField(blank=True, db_column='YEAR', max_length=255, null=True)),
                ('actor_ids', models.CharField(blank=True, db_column='ACTOR_IDS', max_length=255, null=True)),
                ('director_ids', models.CharField(blank=True, db_column='DIRECTOR_IDS', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyappUserinfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=16, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.SmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
