# Generated by Django 4.2.10 on 2024-04-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_moviesworked_myappuserinfo_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=16, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
            ],
        ),
        migrations.RenameModel(
            old_name='MoviesWorked',
            new_name='Movies',
        ),
        migrations.DeleteModel(
            name='MyappUserinfo',
        ),
    ]
