# Generated by Django 4.2.10 on 2024-04-20 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_userinfo_rename_moviesworked_movies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(blank=True, db_column='comment_id', max_length=255, null=True)),
                ('user_md5', models.CharField(blank=True, db_column='user_md5', max_length=255, null=True)),
                ('movie_id', models.CharField(blank=True, db_column='movie_id', max_length=255, null=True)),
                ('content', models.CharField(blank=True, db_column='content', max_length=8000, null=True)),
                ('votes', models.IntegerField(blank=True, db_column='', null=True)),
                ('comment_time', models.DateField(db_column='comment_time')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Douban_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(blank=True, db_column='comment_id', max_length=255, null=True)),
                ('user_md5', models.CharField(blank=True, db_column='user_md5', max_length=255, null=True)),
                ('movie_id', models.CharField(blank=True, db_column='movie_id', max_length=255, null=True)),
                ('content', models.CharField(blank=True, db_column='content', max_length=8000, null=True)),
                ('votes', models.IntegerField(blank=True, db_column='', null=True)),
                ('comment_time', models.DateField(db_column='comment_time')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Douban_UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_md5', models.CharField(blank=True, db_column='user_md5', max_length=255, null=True)),
                ('user_nickname', models.CharField(blank=True, db_column='user_nickname', max_length=255, null=True)),
            ],
        ),
    ]
