# Generated by Django 4.2.10 on 2024-04-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_comments_douban_comments_douban_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.CharField(blank=True, db_column='comment_time', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.CharField(blank=True, db_column='rating', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='douban_comments',
            name='comment_time',
            field=models.CharField(blank=True, db_column='comment_time', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='douban_comments',
            name='rating',
            field=models.CharField(blank=True, db_column='rating', max_length=255, null=True),
        ),
    ]
