# Generated by Django 4.2.10 on 2024-04-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_alter_comments_comment_time_alter_comments_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='douban_userinfo',
            name='user_nickname',
            field=models.CharField(blank=True, db_column='user_nickname', help_text='CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci', max_length=255, null=True),
        ),
    ]
