# Generated by Django 4.2.10 on 2024-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_alter_douban_userinfo_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='douban_userinfo',
            name='user_nickname',
            field=models.CharField(blank=True, db_column='user_nickname', default='匿名用户', max_length=255),
        ),
    ]
