# Generated by Django 4.2.10 on 2024-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_alter_douban_userinfo_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_md5',
            field=models.CharField(blank=True, db_column='user_md5', max_length=255, null=True),
        ),
    ]
