# Generated by Django 4.2.10 on 2024-05-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_userinfo_user_md5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Douban_ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_id', models.CharField(max_length=50, verbose_name='id')),
                ('user_md5', models.CharField(blank=True, db_column='user_md5', max_length=255, null=True)),
                ('movie_id', models.CharField(blank=True, db_column='movie_id', max_length=255, null=True)),
                ('rating', models.CharField(blank=True, db_column='rating', max_length=255, null=True)),
                ('rating_time', models.CharField(blank=True, db_column='rating_time', max_length=255, null=True)),
            ],
            options={
                'verbose_name': '评分信息',
                'verbose_name_plural': '评分信息',
                'db_table': 'Douban_ratings',
            },
        ),
    ]
