# Generated by Django 4.2.10 on 2024-05-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='rating',
        ),
        migrations.AddField(
            model_name='comments',
            name='movie_name',
            field=models.CharField(blank=True, db_column='NAME', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='movie_name',
            field=models.CharField(blank=True, db_column='NAME', max_length=255, null=True),
        ),
    ]
