# Generated by Django 4.2.10 on 2024-05-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_remove_comments_rating_comments_movie_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='movie_name',
            field=models.CharField(blank=True, db_column='movie_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='movie_name',
            field=models.CharField(blank=True, db_column='movie_name', max_length=255, null=True),
        ),
    ]
