# Generated by Django 4.2.10 on 2024-05-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_alter_comments_movie_name_alter_ratings_movie_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255, verbose_name='电影名称')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('box', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='票房')),
                ('area', models.CharField(max_length=255, verbose_name='国家地区')),
                ('main_genre', models.CharField(max_length=255, verbose_name='主要类型')),
                ('genre', models.CharField(max_length=100, verbose_name='类型')),
                ('duration', models.PositiveIntegerField(verbose_name='片长')),
                ('director', models.CharField(max_length=100, verbose_name='导演')),
                ('actors', models.CharField(max_length=255, verbose_name='演员')),
            ],
            options={
                'verbose_name': '票房信息',
                'verbose_name_plural': '票房信息',
                'db_table': 'movie_box',
            },
        ),
    ]
